config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home" 
  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"  
  get "signup"  => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :results        ,only:[:index,:show]  
  resources :categories    ,only:[:index]
  resources :lessons       ,except: [:index,:edit, :destroy]
  resources :words         ,only:[:index] 
  resources :users         ,except: [:index, :destroy]
  
  namespace :admin do
    root "users#index"    
    get "login" => "sessions#new"
    post "login" => "sessions#create"  
    delete "logout" => "sessions#destroy"      
    resources :categories
    resources :words
    resources :users
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home  	
    if logged_in?  	 	
      @lesson  = current_user.lessons.build      
      @activity_lessons = current_user.activity.paginate(page: params[:page])
    end
  end  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
  <center>
    <h3>Welcome to E-Learning System About Page</h3>
    <p>This is about pages</p>	
  </center>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
  <center>
	<h3>Welcome to E-Learning System Contact Page</h3>
	<p>This is contact pages.</p>	
  </center>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
  <center>
	<h3>Welcome to E-Learning System Help Page</h3>	
	<p>This is help page</p>
  </center>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
  <% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">  
        <section class="user_info">      
          <%= render "shared/user_info" %>
        </section>      
      </aside>
      <div class="col-md-8 user_style">
    	<div>
	  	  <%= link_to "Words", words_path, class: "btn btn-lg btn-primary" %>
	  	  <%= link_to "Lesson", categories_path, class: "btn btn-lg btn-primary" %>
        </div>    
        <h3>Activities</h3>   
        <hr/>   
        <%= render "shared/activity" %>
      </div>
    </div>                
  <% else %>
	<center>
	  <h1>Welcome to E-Learning System</h1>
		<div>
	  	  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
		</div>
	</center>
  <%end%>