config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home" 
  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"  
  get "signup"  => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :results        ,only:[:index,:show]  
  resources :categories    ,only:[:index]
  resources :lessons       ,except: [:index,:edit, :destroy]
  resources :words         ,only:[:index] 
  resources :users         ,except: [:index, :destroy]
  
  namespace :admin do
    root "users#index"    
    get "login" => "sessions#new"
    post "login" => "sessions#create"  
    delete "logout" => "sessions#destroy"      
    resources :categories
    resources :words
    resources :users
  end

end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category  
  has_many :word_answers , dependent: :destroy
  validates :content, presence: true
  validates :category_id, presence: true
  accepts_nested_attributes_for :word_answers
    
  scope :order_by_created_date,-> { order("created_at DESC")}

  scope :learned_word, ->(user, category) {
    word_id_query = LessonWord.select("word_id")
      .where(lesson_id: Lesson.select("id").where(user_id: user.id))
      .to_sql
    where("id IN (#{word_id_query}) AND category_id = #{category.id}")
  }

  scope :not_learned_word, ->(user, category) {
   word_id_query = LessonWord.select("word_id")
      .where(lesson_id: Lesson.select("id").where(user_id: user.id))
      .to_sql
    where("id NOT IN (#{word_id_query}) AND category_id = #{category.id}") 
  } 
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
before_action :logged_in_user_admin, only:[:index, :edit, :update,:destroy, :show]  
before_action :admin_user, only:[:index, :edit, :update,:destroy, :show]    

  def new  	
    @categories=Category.all  
  	@word=Word.new
  	4.times.each do
      @word.word_answers.build
    end     
    @test=@word.word_answers.count     
  end

  def create
  	@word=Word.new word_params      	    
    if @word.save        
      flash[:success]="Word #{@word.content} created!"        
      render "show"
    else 
      @categories=Category.all  
      render "new"
    end
  end

  def edit
  	@word=Word.find params[:id]
    @categories=Category.all
  end

  def update
  	@word=Word.find params[:id]     
    if @word.update_attributes word_params            
      render "show"
    else      
      @categories=Category.all
      render "edit"
    end 
  end

  def show
  	@word=Word.find params[:id]
  end

  def index
  	@words=Word.order_by_created_date.paginate page: params[:page], per_page: 20
  end

  def destroy
  	word=Word.find params[:id]    
    flash[:success]="Word #{word.content} delete"    
    word.destroy
    redirect_to admin_words_url
  end

 private     
 
  def word_params
    params.require(:word).permit :id, :content,:category_id,word_answers_attributes: [:id, :content,:correct]
   end

   def admin_user
      redirect_to admin_root_url unless current_user.isadmin?            
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user, only:[:index]
	
  def index		
		@words=nil	
		@categories = Category.all
    	if params[:category_id]
      	@category = Category.find params[:category_id]	
      	@option=params[:condition]
      	case @option    	
        when "learned" 

          @words=Word.learned_word current_user,@category

        when "notlearned"      			      			

          @words=Word.not_learned_word current_user,@category

        when "all"

      		@words=@category.words
          
      	end
      end      
	end
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/views/admin/words/_fields.html.erb
<%= render "shared/error_messages" ,object: f.object %>
  <%= f.label "Category" %>
  <%= f.select(:category_id,options_from_collection_for_select(@categories, "id", "name", @word.category.nil? ? (params[:category_id].nil? ? 1 : params[:category_id]) : @word.category.id ),class: "form-control") %>	
  <%= f.label :content %>
  <%= f.text_field :content, class: "form-control field_info" %>      
  <%=f.fields_for :word_answers do |f2|%>
    <%= f2.label "Meaning #{f2.index+1}" %>    
    <table width="100%">
      <tr>
        <td width="80%"><%= f2.text_field :content, class: "form-control field_info" %></td>
        <td width="5%"><%= f2.check_box :correct,class: "rdoc" %></td>
	      <td width="15%"><%= f2.label :correct,"Right"%></td>        
      </tr>
    </table>
  <%end%>
  <script type="text/javascript">        
      $(".rdoc").on("click", function(){                        	      	      
      	$("input:checkbox").attr("checked", false);      	
      	$(this).prop('checked', true);
      });      
  </script>

app/views/admin/words/_word.html.erb
<li id="word-<%= word.id %>">   
    <span class="content">  
      <%= link_to word.content, admin_word_path(word) %>
  	</span>  
</li>

app/views/admin/words/edit.html.erb
<% provide(:title, "Edit word") %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">    
     <h1 class="account_info">Update <%=@word.content%></h1>
      <%= form_for [:admin, @word] do |f| %>    
        <%=render "fields", f: f%>      
        <%= f.submit "Save changes", class: "btn btn-primary btn_commit" %>
      <% end %>          
    </div>
  </div>

app/views/admin/words/index.html.erb
<% provide(:title, 'All Words') %>
  <h1>All words</h1>
  <%= will_paginate %>
  <ul class="users">
  	<ul class="words">
  	  <%= render @words %>
	</ul>
  </ul>
  <%= will_paginate %>

app/views/admin/words/new.html.erb
<% provide(:title, "New Word") %>  
  <div class="row">
  	<div class="col-md-6 col-md-offset-3">    
  	  <h1>New Word</h1>  	
      <%= form_for [:admin,@word] do |f| %>              
      	<%=render "fields",f: f%>        
      	<%= f.submit "Create User Word", class: "btn btn-primary" %>
      <% end %>
  	</div>
  </div>  

app/views/admin/words/show.html.erb
<% provide(:title, @word.content) %>
  <div class="word_answers">   
    <table>
      <caption><h3><%=@word.content%></h3></caption>
      <%@word.word_answers.each do |word_answer|%>
        <tr>
          <td><b><%=word_answer.content%></b></td>
          <td><div class="<%=word_answer.correct? ? "glyphicon glyphicon-ok success-sign" : "glyphicon glyphicon-remove danger-sign"%>"></td>
        </tr>
      <%end%>
    </table>    
    <p>In category <%=@word.category.nil? ? "No In Any Category" : (link_to @word.category.name, admin_category_path(@word.category))%>        
    </p>
    <%= link_to "Update this word", edit_admin_word_path(@word),class:"btn btn btn-warning"%>        
    <%=link_to "Delete this Word", admin_word_path(@word), method: :delete, data: {confirm: "You sure?"},class:"btn btn btn-danger"%>
  </div>