config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home" 
  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"  
  get "signup"  => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :results        ,only:[:index,:show]  
  resources :categories    ,only:[:index]
  resources :lessons       ,except: [:index,:edit, :destroy]
  resources :words         ,only:[:index] 
  resources :users         ,except: [:index, :destroy]
  
  namespace :admin do
    root "users#index"    
    get "login" => "sessions#new"
    post "login" => "sessions#create"  
    delete "logout" => "sessions#destroy"      
    resources :categories
    resources :words
    resources :users
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :logged_in_user, only:[:index,:show]

  def show
    @lesson_result=Lesson.find params[:id]
  end

  def index
    @lesson_results=current_user.lessons.order_by_created_date.paginate page: params[:page], per_page: 5
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_result.html.erb
<% @lesson_results.each do |lesson_result| %>
  <li>  
    <%= link_to gravatar_for(lesson_result.user, size: 50), lesson_result.user %>  
    <span class="user"><%= link_to lesson_result.user.name, lesson_result.user %>
      <span class="content">      
        got <%=lesson_result.result%>/<%=lesson_result.lesson_words.count%> words in Lesson "<%=lesson_result.category.name%>"   
        -( <%= Date.parse (lesson_result.created_at.to_s) %>)
        <%= link_to "View Result", result_path(lesson_result), class: "" %>
      </span>
    </span> 
  </li>
<% end %>

app/views/results/index.html.erb
<% provide(:title, "Results") %>
  <h3>Lessons's Result</h3>  
    <ul class="users">
  	  <ul class="result">
  	    <%= render "result"%>
	  </ul>
    </ul>
  <%= will_paginate @lesson_results%>

app/views/results/show.html.erb
<% provide(:title, "Result of #{@lesson_result.category.name}")%>	
	 <table border="1" width="50%" align="center">
      <caption><h1><%=@lesson_result.category.name%> Result <%=@lesson_result.result%>/<%=@lesson_result.lesson_words.count%></h1></caption>
      <tr width="20%">
        <th>Word</th>
        <th>Your answer(in italic)</th>                  
        <th>Result</th>
      </tr>
      <%@lesson_result.lesson_words.each do |lesson_word|%>	  
        <tr>                  
          <td><b><%=lesson_word.word.content%></b></td>
          <td><i><%=lesson_word.word_answer.content%></i></td>                  
          <td><div class="<%=lesson_word.word_answer.correct? ? "glyphicon glyphicon-ok success-sign" : "glyphicon glyphicon-remove danger-sign"%>"></div></td>
        </tr>
      <% end %>   
    </table> 
    <br/>
    <center><%= link_to "Start Next Lesson", categories_path, class: "btn btn-primary" %></center>