config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home" 
  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"  
  get "signup"  => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :results        ,only:[:index,:show]  
  resources :categories    ,only:[:index]
  resources :lessons       ,except: [:index,:edit, :destroy]
  resources :words         ,only:[:index] 
  resources :users         ,except: [:index, :destroy]
  
  namespace :admin do
    root "users#index"    
    get "login" => "sessions#new"
    post "login" => "sessions#create"  
    delete "logout" => "sessions#destroy"      
    resources :categories
    resources :words
    resources :users
  end

end

app/models/category.rb
class Category < ActiveRecord::Base	
  has_many :lessons	, dependent: :destroy
  has_many :words	, dependent: :destroy
  validates :name, presence: true

  scope :order_by_created_date,-> { order("created_at DESC")}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController  
before_action :logged_in_user_admin, only:[:index, :edit, :update,:destroy, :show]  
before_action :admin_user, only:[:index, :edit, :update,:destroy, :show]  

  def new  	
  	@category=Category.new
  end
  
  def create
  	@category=Category.new category_params    
    if @category.save                   
      flash[:success]="Category #{@category.name}created!"        
      render "show"
    else 
      render "new"
    end
  end

  def index  	
  	@categories=Category.order_by_created_date.paginate page: params[:page], per_page: 10    
  end

  def show
  	@category=Category.find params[:id]
  	@words=@category.words.order_by_created_date.paginate page: params[:page], per_page: 20    
  end

  def edit
  	@category=Category.find params[:id]
  end

  def update
  	@category = Category.find params[:id]    
    @words=@category.words.order_by_created_date.paginate page: params[:page], per_page: 20    
    if @category.update_attributes category_params      
      flash[:success]="Category update"      
      render "show"
    else      
      render "edit"
    end
  end

  def destroy
  	category=Category.find params[:id]    
    flash[:success]="Category #{category.name} delete"    
    category.destroy
    redirect_to admin_categories_url
  end

  private    
    def category_params
      params.require(:category).permit(:name,:description)
    end    
    def admin_user
      redirect_to admin_root_url unless current_user.isadmin?            
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, only:[:index]

  def index  
    @categories = Category.paginate page: params[:page], per_page: 5           
  end  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<li id="category-<%= category.id %>">   
  <span class="content">  
	<%= link_to category.name, admin_category_path(category)%>	
  </span>
</li>

app/views/admin/categories/_fields.html.erb
 <%= render "shared/error_messages" ,object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control field_info" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control field_info" %>

app/views/admin/categories/edit.html.erb
<% provide(:title, "Edit Category") %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">    
     <h1 class="account_info">Update <%=@category.name%> </h1>
      <%= form_for [:admin, @category] do |f| %>    
        <%=render "fields", f: f%>      
        <%= f.submit "Save changes", class: "btn btn-primary btn_commit" %>
      <% end %>    
    </div>      
  </div>

app/views/admin/categories/index.html.erb
<% provide(:title, "Categories") %>
  <h1>All categories</h1>
  <%= will_paginate %>
  <ul class="users">
  	<ul class="categories">
  	  <%= render @categories %>
	</ul>
  </ul>
  <%= will_paginate %>

app/views/admin/categories/new.html.erb
<% provide(:title, "New Category") %>  
  <div class="row">
  	<div class="col-md-6 col-md-offset-3">    
  	  <h1>New Category</h1>
      <%= form_for [:admin,@category] do |f| %>      
      	<%=render "fields",f: f%>        
      	<%= f.submit "Create Category", class: "btn btn-primary" %>
      <% end %>
  	</div>
  </div>

app/views/admin/categories/show.html.erb
<% provide(:title, @category.name) %>  
  <div class="row">
    <aside class="col-md-4">  
      <section class="user_info">
        <h3><%=@category.name%></h3>
        <p><%=@category.description%></p>
        <%= link_to "Add New Word", new_admin_word_path(category_id: @category.id) ,class:"btn btn-primary"%>
        <%= link_to "Update this category", edit_admin_category_path(@category),class:"btn btn btn-warning"%>
        <div style="padding-top:5px; padding-left:20%">
          <%=link_to "Delete this category", admin_category_path(@category), method: :delete, data: {confirm: "You sure?"},class:"btn btn btn-danger"%>
        </div>
      </section>    
    </aside>                            
    <div class="col-md-8 user_style">      
      <% if @category.words.any? %>  
        <h3>Words</h3>      
        <ul class="users">
          <ul class="words">
            <%= render @words %>
          </ul>
        </ul>  
        <%= will_paginate @words %>
      <% end %>
    </div>
  </div>